# Generated by Django 2.2 on 2019-05-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190501_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='created_by',
            new_name='owner',
        ),
    ]
